/**
 * infiniterm's OpenCode adapter: reports this session's state to the card it
 * runs in (issue #25).
 *
 * Installed by `ift install-opencode-hooks` into ~/.config/opencode/plugins/
 * (or $XDG_CONFIG_HOME/opencode/plugins/). The hook path below is filled in at
 * install time; do not edit this file in place, the next install rewrites it.
 *
 * It speaks Claude Code's hook vocabulary, as the Pi adapter does: infiniterm
 * maps event NAMES to card state (agent_state.rs) and the hook binary forwards
 * whatever it is given, with "opencode" after the event so the card knows
 * whose session it holds (`opencode --session <id>` after a reboot).
 *
 * OpenCode's events, from its source (v1.18): `session.status` busy is a turn
 * running, `session.idle` its end, `session.error` a failure (an Esc arrives
 * as MessageAbortedError, which is not one), `permission.asked` and
 * `question.asked` the agent waiting on you. A sub-agent's sessions (those
 * with a parentID) are left out, or a task tool finishing would turn the card
 * done mid-turn. OpenCode keeps sessions in SQLite, so there is no transcript
 * path to report.
 *
 * Does nothing outside a card (no INFINITERM_CARD_ID), and never throws: a
 * status report must not be able to break a turn.
 */
import { spawn } from "node:child_process";

const HOOK = "__INFINITERM_HOOK__";

export const InfinitermPlugin = async () => {
  if (!process.env.INFINITERM_CARD_ID) return {};

  // One report at a time, in order: a Stop overtaking a PreToolUse would
  // leave the card lit as working after the turn ended. Never awaited by
  // OpenCode, so a slow hook cannot stall a turn.
  let queue = Promise.resolve();
  const report = (event, sessionID) => {
    const payload = JSON.stringify({
      hook_event_name: event,
      session_id: sessionID ?? null,
      cwd: process.cwd(),
    });
    queue = queue.then(
      () =>
        new Promise((done) => {
          try {
            const child = spawn(HOOK, [event, "opencode"], { stdio: ["pipe", "ignore", "ignore"] });
            child.on("error", () => done());
            child.on("close", () => done());
            child.stdin.on("error", () => {});
            child.stdin.end(payload);
          } catch {
            done(); // a missing hook binary is not OpenCode's problem
          }
        }),
    );
  };

  const children = new Set();
  const mine = (id) => Boolean(id) && !children.has(id);
  // A failed turn still ends with `session.idle`; it must not turn the card
  // from failed to done.
  let failed = false;

  return {
    event: async ({ event }) => {
      try {
        const p = event.properties ?? {};
        switch (event.type) {
          case "session.created":
            if (p.info?.parentID) children.add(p.info.id);
            else report("SessionStart", p.info?.id);
            return;
          case "session.deleted":
            if (!children.delete(p.info?.id)) report("SessionEnd", p.info?.id);
            return;
          case "session.status":
            if (mine(p.sessionID) && p.status?.type === "busy") {
              failed = false;
              report("UserPromptSubmit", p.sessionID);
            }
            return;
          case "permission.asked":
          case "question.asked":
            if (mine(p.sessionID)) report("PermissionRequest", p.sessionID);
            return;
          case "session.error":
            if (mine(p.sessionID) && p.error?.name !== "MessageAbortedError") {
              failed = true;
              report("StopFailure", p.sessionID);
            }
            return;
          case "session.idle":
            if (!mine(p.sessionID)) return;
            if (failed) failed = false;
            else report("Stop", p.sessionID);
            return;
        }
      } catch {
        // never break OpenCode over a status report
      }
    },
    "tool.execute.before": async (input) => {
      if (mine(input?.sessionID)) report("PreToolUse", input.sessionID);
    },
    "tool.execute.after": async (input) => {
      if (mine(input?.sessionID)) report("PostToolUse", input.sessionID);
    },
  };
};
