/**
 * infiniterm's Pi adapter: reports this session's state to the card it runs in.
 *
 * Installed by `ift install-pi-hooks` into an agent dir's extensions/ (the
 * default ~/.pi/agent, or whatever PI_CODING_AGENT_DIR points at — a wrapper
 * like `pig` runs Pi against its own dir and needs its own copy). The hook
 * path below is filled in at install time; do not edit this file in place,
 * the next install rewrites it.
 *
 * It speaks Claude Code's hook vocabulary on purpose: infiniterm maps event
 * NAMES to card state (agentState.ts) and the hook binary forwards whatever
 * it is given, so an adapter is the name mapping and nothing else. Every
 * report carries the session file, which is what the transcript card reads.
 *
 * Does nothing outside a card (no INFINITERM_CARD_ID in the environment),
 * and never throws: a status report must not be able to break a turn.
 */
import { spawn } from "node:child_process";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

const HOOK = "__INFINITERM_HOOK__";

export default function (pi: ExtensionAPI) {
  if (!process.env.INFINITERM_CARD_ID) return;

  // One report at a time, in order. Two spawned together can reach the
  // socket in either order, and a Stop overtaking a PreToolUse would leave
  // the card lit as working after the turn had ended. Never awaited by Pi:
  // the queue is the adapter's own, so a slow hook cannot stall a turn.
  let queue: Promise<void> = Promise.resolve();
  const report = (event: string, ctx: ExtensionContext, extra: Record<string, unknown> = {}) => {
    const payload = JSON.stringify({
      hook_event_name: event,
      transcript_path: ctx.sessionManager.getSessionFile() ?? null,
      cwd: ctx.cwd,
      ...extra,
    });
    queue = queue.then(
      () =>
        new Promise<void>((done) => {
          try {
            const child = spawn(HOOK, [event, "pi"], { stdio: ["pipe", "ignore", "ignore"] });
            child.on("error", () => done());
            child.on("close", () => done());
            child.stdin.on("error", () => {});
            child.stdin.end(payload);
          } catch {
            done(); // a missing hook binary is not Pi's problem
          }
        }),
    );
  };

  pi.on("session_start", (_e, ctx) => report("SessionStart", ctx));
  // agent_start is the prompt going in; agent_settled is Pi with nothing
  // left to do on its own — agent_end can be followed by a retry or a
  // queued follow-up, which is still "working" from across the room.
  pi.on("agent_start", (_e, ctx) => report("UserPromptSubmit", ctx));
  pi.on("tool_execution_start", (e, ctx) => report("PreToolUse", ctx, { tool_name: e.toolName }));
  pi.on("tool_execution_end", (e, ctx) => report("PostToolUse", ctx, { tool_name: e.toolName }));
  // A question on screen is Pi waiting on you, whatever the agent loop is doing.
  pi.on("ui_prompt_start", (_e, ctx) => report("Notification", ctx));
  pi.on("agent_settled", (_e, ctx) => report("Stop", ctx));
  pi.on("session_shutdown", (_e, ctx) => report("SessionEnd", ctx));
}
