const out = [];
const log = (k, v) => { out.push(k + ' = ' + (typeof v === 'string' ? v : JSON.stringify(v))); document.getElementById('o').textContent = out.join('\n'); };
const T = (p, ms = 3000) => Promise.race([p, new Promise((_, r) => setTimeout(() => r(new Error('timeout')), ms))]);
const run = async (k, f) => { try { log(k, await T(Promise.resolve().then(f))); } catch (e) { log(k, 'ERR ' + String(e.message || e).slice(0, 90)); } };
(async () => {
  const v = document.createElement('video');
  const aud = document.createElement('audio');
  log('--- codecs', '');
  for (const t of ['video/mp4; codecs="avc1.42E01E"', 'video/mp4; codecs="avc1.640028,mp4a.40.2"', 'video/mp4; codecs="hvc1.1.6.L93.B0"', 'video/webm; codecs="vp9"', 'video/mp4; codecs="av01.0.05M.08"', 'video/webm; codecs="vp8"']) log('canPlayType ' + t, v.canPlayType(t) || '(empty)');
  for (const t of ['audio/mp4; codecs="mp4a.40.2"', 'audio/mpeg', 'audio/ogg; codecs="opus"']) log('audio ' + t, aud.canPlayType(t) || '(empty)');
  log('MSE avc1', window.MediaSource ? MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E,mp4a.40.2"') : 'no MediaSource');
  log('--- drm / auth / media', '');
  await run('widevine', async () => { const a = await navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{ initDataTypes: ['cenc'], videoCapabilities: [{ contentType: 'video/mp4; codecs="avc1.42E01E"' }] }]); return 'ok ' + a.keySystem; });
  await run('PublicKeyCredential', () => typeof window.PublicKeyCredential);
  await run('platform authenticator', () => PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable());
  await run('mediaDevices', () => typeof navigator.mediaDevices);
  await run('getDisplayMedia', () => typeof (navigator.mediaDevices && navigator.mediaDevices.getDisplayMedia));
  await run('Notification.permission', () => Notification.permission);
  await run('geolocation', () => typeof navigator.geolocation);
  log('--- chrome namespaces present', Object.keys(chrome).sort().join(' '));
  log('--- chrome.action', '');
  await run('action.setBadgeText', () => chrome.action.setBadgeText({ text: '7' }).then(() => 'ok'));
  await run('action.getBadgeText', () => chrome.action.getBadgeText({}));
  await run('action.setTitle', () => chrome.action.setTitle({ title: 't' }).then(() => 'ok'));
  await run('action.onClicked', () => typeof chrome.action.onClicked.addListener);
  await run('action.getUserSettings', () => chrome.action.getUserSettings());
  await run('action.openPopup', () => typeof chrome.action.openPopup);
  log('--- other APIs', '');
  await run('contextMenus.create', () => new Promise((res, rej) => { chrome.contextMenus.create({ id: 'x', title: 'x', contexts: ['all'] }, () => chrome.runtime.lastError ? rej(chrome.runtime.lastError) : res('ok')); }));
  await run('commands.getAll', () => chrome.commands.getAll());
  await run('notifications.create', () => new Promise((res, rej) => chrome.notifications.create('n', { type: 'basic', iconUrl: 'data:image/png;base64,iVBORw0KGgo=', title: 't', message: 'm' }, (id) => chrome.runtime.lastError ? rej(chrome.runtime.lastError) : res('ok ' + id))));
  await run('downloads.search', () => chrome.downloads.search({}).then((r) => r.length + ' items'));
  await run('bookmarks.getTree', () => chrome.bookmarks.getTree().then((r) => 'nodes ' + r.length));
  await run('history.search', () => chrome.history.search({ text: '', maxResults: 3 }).then((r) => r.length + ' items'));
  await run('sessions.getRecentlyClosed', () => chrome.sessions.getRecentlyClosed().then((r) => r.length + ' items'));
  await run('topSites.get', () => chrome.topSites.get().then((r) => r.length + ' items'));
  await run('cookies.getAll', () => chrome.cookies.getAll({}).then((r) => r.length + ' cookies'));
  await run('management.getAll', () => chrome.management.getAll().then((r) => r.map((e) => e.name).join(', ')));
  await run('identity.getRedirectURL', () => chrome.identity.getRedirectURL());
  await run('sidePanel', () => typeof (chrome.sidePanel && chrome.sidePanel.setOptions));
  await run('declarativeNetRequest', () => chrome.declarativeNetRequest.getDynamicRules().then((r) => r.length + ' rules'));
  await run('tabGroups.query', () => chrome.tabGroups.query({}).then((r) => r.length + ' groups'));
  await run('offscreen', () => typeof (chrome.offscreen && chrome.offscreen.createDocument));
  await run('windows.create', () => chrome.windows.create({ url: 'about:blank' }).then((w) => 'window ' + w.id));
  await run('tabs.create', () => chrome.tabs.create({ url: 'about:blank' }).then((t) => 'tab ' + t.id));
  await run('system.display', () => typeof (chrome.system && chrome.system.display));
})();
